<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.png">
    <title>Simple PHP MVC</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
<section>
    <div>
        <?php foreach ($categories as $category) { ?>
            <h2> <?php echo $category['name'] . ' || ' ?></h2>
        <?php } ?>
    </div>
</section>
<section>
    <h1>My posts:</h1>
    <?php foreach ($posts as $post) { ?>
        <h2> <?php echo $post['title'] ?></h2>
        <span> <?php  echo $post['content'] ?></span>

        <span><br>------------------------<br></span>
    <?php } ?>
</body>

</html>