<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.png">
    <title>Simple PHP MVC</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
      .parent-category {
        font-size: 50px;
      }
      .category .child-categories {
        display: none;
      }

      .category:hover .child-categories {
        display: block;
      }
    </style>
</head>

<body>
<section>
    <div>
        <?php foreach ($parentCategories as $category) { ?>
            <div class="category">
                <h2> <?php echo $category['name'] . ' || ' ?></h2>
                <div class="child-categories">
                    <?php foreach ($childCategories as $child) { ?>
                        <?php if ($child['parent_id'] == $category['id']) { ?>
                            <?php echo $child['name'] . ' XXXXX ' ?>
                        <?php } ?>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</section>

<hr>
<br>
<br>
<br>
<br>
<br>

<section>
<!--    <h1>My posts:</h1>-->
<!--    --><?php //foreach ($posts as $post) { ?>
<!--        <h2> --><?php //echo $post['title'] ?><!--</h2>-->
<!--        <span> --><?php //echo $post['content'] ?><!--</span>-->
<!---->
<!--        <span><br>------------------------<br></span>-->
<!--    --><?php //} ?>

    <div>
        <h2>Giới thiệu</h2>
            <h1>My posts:</h1>
            <?php foreach ($gioiThieu as $post) { ?>
                <h2> <?php echo $post['title'] ?></h2>
                <span> <?php echo $post['content'] ?></span>

                <span><br>------------------------<br></span>
            <?php } ?>
    </div>
    <hr>
    <br>
    <br>
    <br>

    <div>
        <h2>Thông báo</h2>
        <?php foreach ($thongBao as $post) { ?>
            <h2> <?php echo $post['title'] ?></h2>
            <span> <?php echo $post['content'] ?></span>

            <span><br>------------------------<br></span>
        <?php } ?>
    </div>
    <hr>
    <br>
    <br>
    <br>

    <div>
        <h2>Bản tin</h2>
        <?php foreach ($banTin as $post) { ?>
            <h2> <?php echo $post['title'] ?></h2>
            <span> <?php echo $post['content'] ?></span>

            <span><br>------------------------<br></span>
        <?php } ?>
    </div>
</body>

</html>